### ISSUE TITLE
adding localedir

### ISSUE THREAD

**Issue by andy5995** [SlackBuildsOrg/templates#3]
https://github.com/SlackBuildsOrg/templates/blob/2dbac016f564b0fe57019b56c2b1b176b4c3ebe9/autotools-template.SlackBuild#L125

I wonder adding `--localedir` to the configure options wouldn't be good, or at a minimum, a comment reminding the maintainer that if the package includes translations, to add it to the configure line.

**Comment by willysr** [comment]
translations should go to /usr/share/locale but not every project have translations, FYI
